// src/modules/mavin-engine/index.ts
/**
 * MavinEngine Native Module Wrapper
 * 
 * Single source of truth JS/TS bridge for YouTube/NewPipe extraction.
 * Provides access to trending content, stream info, and search.
 * 
 * Architecture: v10.1.0
 * - getCookieHeader() consent pattern (official DownloaderImpl)
 * - No CookieJar (SOCS cookie injected per-request)
 * - AccountTerminatedException handling
 * - iOS client responses for better stream availability
 */

import { requireNativeModule } from 'expo-modules-core';

const Native = requireNativeModule('MavinEngine');

if (!Native) {
  console.error('[MavinEngine] CRITICAL: native module not loaded.');
}

// ─────────────────────────────────────────────────────────────────────────────
// TYPES
// ─────────────────────────────────────────────────────────────────────────────

export interface NativeImage {
  url: string;
  width: number;
  height: number;
  resolutionLevel: 'UNKNOWN' | 'LOW' | 'MEDIUM' | 'HIGH' | 'VERY_HIGH';
}

export interface NativePage {
  url: string;
  ids: string[];
  cookies: Record<string, string>;
}

export interface StreamInfoItem {
  type: 'stream';
  serviceId: number;
  url: string;
  name: string;
  uploaderName: string;
  uploaderUrl: string;
  uploaderVerified: boolean;
  thumbnails: NativeImage[];
  duration: number;
  viewCount: number;
  textualUploadDate: string;
  streamType: 'VIDEO_STREAM' | 'AUDIO_STREAM' | 'LIVE_STREAM' | 'AUDIO_LIVE_STREAM' | 'POST_LIVE_STREAM' | 'POST_LIVE_AUDIO_STREAM' | 'NONE';
  isLive: boolean;
  isShortFormContent: boolean;
}

export interface PlaylistInfoItem {
  type: 'playlist';
  serviceId: number;
  url: string;
  name: string;
  uploaderName: string;
  uploaderUrl: string;
  thumbnails: NativeImage[];
  streamCount: number;
  playlistType: string;
}

export interface ChannelInfoItem {
  type: 'channel';
  serviceId: number;
  url: string;
  name: string;
  thumbnails: NativeImage[];
  subscriberCount: number;
  streamCount: number;
  isVerified: boolean;
  description: string;
}

export type InfoItem = StreamInfoItem | PlaylistInfoItem | ChannelInfoItem;

export interface AudioStream {
  url: string;
  isUrl: boolean;
  deliveryMethod: string;
  format: string;
  codec: string;
  bitrate: number;
  audioTrackId: string;
  audioTrackName: string;
  audioLocale: string;
  audioTrackType: string;
  manifestUrl: string;
}

export interface VideoStream {
  url: string;
  isUrl: boolean;
  deliveryMethod: string;
  format: string;
  codec: string;
  width: number;
  height: number;
  fps: number;
  bitrate: number;
  quality: string;
  manifestUrl: string;
}

export interface SubtitleStream {
  url: string;
  isUrl: boolean;
  deliveryMethod: string;
  format: string;
  languageTag: string;
  displayLanguageName: string;
  isAutoGenerated: boolean;
  manifestUrl: string;
}

export interface StreamInfo {
  success: boolean;
  error?: string;
  message?: string;
  serviceId: number;
  id: string;
  url: string;
  originalUrl: string;
  title: string;
  uploaderName: string;
  uploaderUrl: string;
  uploaderAvatars: NativeImage[];
  uploaderVerified: boolean;
  uploaderSubscriberCount: number;
  duration: number;
  viewCount: number;
  likeCount: number;
  dislikeCount: number;
  description: string;
  uploadDate: string;
  textualUploadDate: string;
  thumbnails: NativeImage[];
  streamType: string;
  isLive: boolean;
  isShortFormContent: boolean;
  availability: string;
  ageLimit: number;
  tags: string[];
  category: string;
  startPosition: number;
  host: string;
  privacy: string;
  licence: string;
  languageInfo: string;
  audioStreams: AudioStream[];
  videoStreams: VideoStream[];
  videoOnlyStreams: VideoStream[];
  dashMpdUrl: string;
  hlsUrl: string;
  subtitles: SubtitleStream[];
  relatedItems: InfoItem[];
  errors: string[];
}

export interface TrendingResult {
  success: boolean;
  source: string;
  items: InfoItem[];
  totalAvailable: number;
  errors: string[];
  message?: string;
}

export interface ResolvedUrl {
  type: 'stream' | 'channel' | 'playlist' | 'none';
  id: string;
  url: string;
  serviceId: number;
  serviceName: string;
}

export interface PingResult {
  alive: boolean;
  version: string;
  timestamp: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// API FUNCTIONS
// ─────────────────────────────────────────────────────────────────────────────

export const getTrendingWithFallback = (
  category: string = 'music',
  serviceId: number = 0
): Promise<TrendingResult> =>
  Native.getTrendingWithFallback(category, serviceId);

export const getStreamInfo = (
  url: string,
  serviceId?: number
): Promise<StreamInfo> =>
  Native.getStreamInfo(url, serviceId ?? null);

export const getStreamInfoById = (
  videoId: string,
  serviceId?: number
): Promise<StreamInfo> =>
  Native.getStreamInfoById(videoId, serviceId ?? null);

export const getStreamUrl = (
  url: string,
  format?: 'audio' | 'video' | 'mp3' | 'm4a' | 'ogg' | 'mp4' | 'best' | 'dash' | 'hls',
  serviceId?: number
): Promise<{
  success: boolean;
  url: string;
  format: string;
  title: string;
  duration: number;
  fallbackUrls: string[];
}> => Native.getStreamUrl(url, format ?? null, serviceId ?? null);

export const resolveUrl = (
  url: string,
  serviceId?: number
): Promise<ResolvedUrl> =>
  Native.resolveUrl(url, serviceId ?? null);

export const ping = (): Promise<PingResult> => Native.ping();
export const version: string = Native.version;
export const initialized: boolean = Native.initialized;

export default {
  getTrendingWithFallback,
  getStreamInfo,
  getStreamInfoById,
  getStreamUrl,
  resolveUrl,
  ping,
  version,
  initialized,
};
